//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PairProgramming.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Employee
    {
		[Display(Name = "Employee ID")]
		public int EmployeeID { get; set; }
		[Display(Name = "Employee Name")]
		public string Employee_Name { get; set; }
		[Display(Name = "Pay Rate")]
		public decimal Pay_Rate { get; set; }
		[Display(Name = "Hours Worked")]
		public double Hours_Worked { get; set; }
    }
}
